---
title: "Data"
author: "Michal Michalski"
format: 
  html:
    code-fold: true
    toc: true
    code-overflow: wrap
editor: visual
execute: 
  warning: false
---

## Archaeological Survey

```{r}

# load libraries
library(sf) # for spatial classes
library(dplyr) # wrangle data
library(stringr) # text wrangling

# read northern mesopotamian sites
n_mes_sites = st_read("../data/raw/north_mesopotamia_sites.shp",quiet = TRUE ) %>% 
  janitor::clean_names() %>% 
  mutate(
   code = str_extract(id, "[^_]+")
  )

# create summary table counting unique sites by survey
surveys_df = n_mes_sites %>% 
  st_drop_geometry() %>% 
  group_by(code, source) %>% 
  summarise(n_sites = n_distinct(id))

# create summary table for mapping
surveys_sf = n_mes_sites %>% 
  group_by(code) %>% 
  summarise(sites = n_distinct(id))

```

Archaeological surveys in the Northern Mesopotamia

```{r}

library(knitr)

knitr::kable(surveys_df)
```

```{r}

library(tmap)

tm_shape(surveys_sf) +
  tm_dots(size = 0.05) +
  tm_layout(main.title = "Archaeological Surveys - Northern Mesopotamia",
            ) +
  tm_scale_bar(position=c("right", "BOTTOM"),) +
  tm_facets(by="code", free.coords = TRUE)


```

## Climate

Precipitation

Temperature

## Soil

## Topography

### Digital Elevation Model

```{r}

dem = terra::rast("../data/rast/njs/dem.tif")

terra::plot(dem)
```

### Slope

```{r}

slope = terra::rast("../data/rast/njs/slope.tif")

terra::plot(slope)
```

### Aspect

```{r}

aspect = terra::rast("../data/rast/njs/aspect.tif")

terra::plot(aspect)
```

### Terrain Position Index

```{r}

tpi = terra::rast("../data/rast/njs/tpi.tif")

terra::plot(tpi)
```

### Compound Topographic Index

```{r}

cti = terra::rast("../data/rast/njs/cti.tif")

terra::plot(cti)

```

#### Geomorphons

```{r}

geomorphon = terra::rast("../data/rast/njs/geom.tif")

terra::plot(geomorphon, type = "classes")

```
